#!C:\Users\mtcd\Documents\Codes\dc3-wss\.venv3\Scripts\python3.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
